development:
  adapter: postgresql
  database: fbuntu_development
  encoding: utf8
  username: kumar
  password: kumar

# test: &TEST
#   adapter: postgresql
#   database: fbuntu_test
#   encoding: utf8
#   username: kumar
#   password: kumar

# cucumber:
#   <<: *TEST
